#!/bin/sh
set -e
package_name=biglinux-wallpapers-and-icons
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/icons/breeze/actions/22/document-print.svg"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/icons/breeze/apps/48/smplayer.svg"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/icons/breeze/apps/48/application-x-clementine.svg"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/icons/breeze/apps/48/org.gnome.Cheese.svg"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/icons/breeze/actions/22/document-print.svg"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/icons/breeze/apps/48/smplayer.svg"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/icons/breeze/apps/48/application-x-clementine.svg"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/icons/breeze/apps/48/org.gnome.Cheese.svg"
;;
esac
exit 0
