#!/bin/sh
set -e
package_name=biglinux-wallpapers-and-icons
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/icons/breeze/actions/22/document-print.svg"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/icons/breeze/actions/22/document-print.svg"
;;
esac
exit 0
