#!/bin/sh
set -e
package_name=biglinux-wallpapers-and-icons
mkdir -p "/usr/share/dpkgdivert/biglinux-wallpapers-and-icons"
case "$1" in
  install)
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/biglinux-wallpapers-and-icons/usrshareiconsbreezeactions22document-print.svg" --rename "/usr/share/icons/breeze/actions/22/document-print.svg"
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/biglinux-wallpapers-and-icons/usrshareiconsbreezeapps48smplayer.svg" --rename "/usr/share/icons/breeze/apps/48/smplayer.svg"
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/biglinux-wallpapers-and-icons/usrshareiconsbreezeapps48application-x-clementine.svg" --rename "/usr/share/icons/breeze/apps/48/application-x-clementine.svg"
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/biglinux-wallpapers-and-icons/usrshareiconsbreezeapps48org.gnome.Cheese.svg" --rename "/usr/share/icons/breeze/apps/48/org.gnome.Cheese.svg"
    ;;
  upgrade)
if [ "$(dpkg-divert --list "/usr/share/icons/breeze/actions/22/document-print.svg")" = "" ]
then
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/biglinux-wallpapers-and-icons/usrshareiconsbreezeactions22document-print.svg" --rename "/usr/share/icons/breeze/actions/22/document-print.svg"
fi
if [ "$(dpkg-divert --list "/usr/share/icons/breeze/apps/48/smplayer.svg")" = "" ]
then
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/biglinux-wallpapers-and-icons/usrshareiconsbreezeapps48smplayer.svg" --rename "/usr/share/icons/breeze/apps/48/smplayer.svg"
fi
if [ "$(dpkg-divert --list "/usr/share/icons/breeze/apps/48/application-x-clementine.svg")" = "" ]
then
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/biglinux-wallpapers-and-icons/usrshareiconsbreezeapps48application-x-clementine.svg" --rename "/usr/share/icons/breeze/apps/48/application-x-clementine.svg"
fi
if [ "$(dpkg-divert --list "/usr/share/icons/breeze/apps/48/org.gnome.Cheese.svg")" = "" ]
then
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/biglinux-wallpapers-and-icons/usrshareiconsbreezeapps48org.gnome.Cheese.svg" --rename "/usr/share/icons/breeze/apps/48/org.gnome.Cheese.svg"
fi
;;
esac
exit 0
